import { studentModel } from "./studentModel";
export const studentsDummyData: studentModel[] = [
  {
    name: "Amit Sharma",
    regNum: "REG001",
    batchStart: "2024-01",
    batchEnd: "2024-06",
    DateOfJoin: new Date("2024-01-10"),
    Course: "Full Stack Development",
    FatherName: "Ramesh Sharma",
    Address: "Delhi, India",
    PhonePrimary: "9876543210",
    dob: new Date("2001-05-12"),
    HighestQualification: "B.Sc",
    Email: "amit.sharma@example.com",
    Fees: 45000,
    isCertified: false,
    isCompleted: false,
    isDeleted: false,
    isFeesPending: true,
    isActive: true
  },
  {
    name: "Neha Verma",
    regNum: "REG002",
    batchStart: "16:00",
    batchEnd: "17:00",
    DateOfJoin: new Date("2024-01-12"),
    Course: "Data Science",
    FatherName: "Suresh Verma",
    Address: "Jaipur, Rajasthan",
    PhonePrimary: "9123456789",
    dob: new Date("2000-11-23"),
    HighestQualification: "B.Tech",
    Email: "neha.verma@example.com",
    Fees: 60000,
    isCertified: false,
    isCompleted: false,
    isDeleted: false,
    isFeesPending: false,
    isActive: true
  },
  {
    name: "Rahul Singh",
    regNum: "REG003",
    batchStart: "2024-02",
    batchEnd: "2024-08",
    DateOfJoin: new Date("2024-02-01"),
    Course: "MERN Stack",
    FatherName: "Mahesh Singh",
    Address: "Lucknow, UP",
    PhonePrimary: "9988776655",
    PhoneSecondary: "8877665544",
    dob: new Date("1999-08-19"),
    HighestQualification: "BCA",
    Email: "rahul.singh@example.com",
    Fees: 50000,
    isCertified: false,
    isCompleted: false,
    isDeleted: false,
    isFeesPending: true,
    isActive: true
  },
  {
    name: "Pooja Patel",
    regNum: "REG004",
    batchStart: "2024-02",
    batchEnd: "2024-08",
    DateOfJoin: new Date("2024-02-05"),
    Course: "UI/UX Design",
    FatherName: "Ketan Patel",
    Address: "Ahmedabad, Gujarat",
    PhonePrimary: "9090909090",
    dob: new Date("2002-02-14"),
    HighestQualification: "B.Des",
    Email: "pooja.patel@example.com",
    Fees: 40000,
    isCertified: false,
    isCompleted: false,
    isDeleted: false,
    isFeesPending: false,
    isActive: true
  },
  {
    name: "Sanjay Kumar",
    regNum: "REG005",
    batchStart: "2023-09",
    batchEnd: "2024-03",
    DateOfJoin: new Date("2023-09-15"),
    Course: "Python Programming",
    FatherName: "Ram Kumar",
    Address: "Patna, Bihar",
    PhonePrimary: "9012345678",
    dob: new Date("1998-06-30"),
    HighestQualification: "M.Sc",
    Email: "sanjay.kumar@example.com",
    Fees: 30000,
    isCertified: true,
    isCompleted: true,
    isDeleted: false,
    isFeesPending: false,
    isActive: false
  },

  // ---- Auto-generated style entries for remaining students ----

  ...Array.from({ length: 25 }).map((_, i) => ({
    name: `Student ${i + 6}`,
    regNum: `REG${String(i + 6).padStart(3, "0")}`,
    batchStart: "2024-03",
    batchEnd: "2024-09",
    DateOfJoin: new Date("2024-03-01"),
    Course: i % 2 === 0 ? "Java Backend" : "Web Development",
    FatherName: `Father ${i + 6}`,
    Address: "India",
    PhonePrimary: `9${Math.floor(100000000 + Math.random() * 900000000)}`,
    dob: new Date(`200${i % 10}-01-01`),
    HighestQualification: i % 3 === 0 ? "B.Tech" : "BCA",
    Email: `student${i + 6}@example.com`,
    Fees: 35000 + (i % 3) * 5000,
    isCertified: false,
    isCompleted: false,
    isDeleted: false,
    isFeesPending: i % 2 === 0,
    isActive: true
  }))
];
